services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: escola
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    ports:
      - "5433:5432"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Porta externa 8080 mapeia para a 80 interna do nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
